### ISSUE TITLE
Resources do not load with Palladium

### ISSUE THREAD

**Issue by GrayStriped** [enjarai/mini-tardis#10]
When the mod Palladium is installed, custom textures and models go missing. Minecraft specifies "Resource reload failed" in the main menu, and attempting to reload resources in-game send me to the main menu.

Attached pictures are with and without Paladium
![2024-03-18_22 17 19](https://github.com/enjarai/mini-tardis/assets/44683183/45210e4b-c4ef-441c-8cf6-41317b767235)
![2024-03-18_22 19 02](https://github.com/enjarai/mini-tardis/assets/44683183/05df679f-33eb-4bfb-b368-390670ecf673)

**Comment by enjarai** [comment]
I'll need a log file to properly diagnose this. Can you also include a link to this Palladium mod? I've never heard of it.

**Comment by GrayStriped** [comment]
[latest.log](https://github.com/enjarai/mini-tardis/files/14653734/latest.log)
https://www.curseforge.com/minecraft/mc-mods/threetag-palladium

The only installed mods are Mini Tardis, Palladium, Fabric API, and JEI

**Comment by GrayStriped** [comment]
Update: the Palladium Github found the problem
https://github.com/ThreeTAG/Palladium/issues/108#issuecomment-2007711679

**Comment by enjarai** [comment]
Fixed in the latest CICADA version. You can manually download and install a newer version of this library from here: https://modrinth.com/mod/cicada/
