### ISSUE TITLE
Put in the Description you added Crash Pipe mod by KikuGie Fabric 1.20.1

### ISSUE THREAD

**Issue by Nate4Fate** [enjarai/mini-tardis#13]
I narrowed down that your mod adds Crash Pipe sound by KikuGie into the .farbic->processed mods and making a config folder called crash-pipe. It definitely was a surprise when it played in game. 

Your TARDIS mod is very fun and unique to use, especially with the fun mini games and floppy disk feature. Not being able to go to different dimensions early on was tough compared to other TARDIS mods, but I understand that it's the only implementation to use the dimension floppy disk in that way. 

My friends and I loved playing with the mod and was going to choose it over Adventures in Time and Doctor Who - Reborn, but the crash pipe sound is way to loud and I can't disable it, had to disable or remove the TARDIS mod in order to get rid of the Crash Pipe sound mod. I don't know if the Crash Pipe sound mod was added on purpose, but you should definitely let others know in the description as the crash pipe sound plays for any crash, not just crashing and force closing the game. I understand, too, if you intended on the crash pipe mod to be a feature with the Mini TARDIS mod. Just let others know at least. Here's a fresh profile log with only Mini Tardis mod installed to prove it, adds crash-pipe 0.1.0

![Screenshot 2024-03-25 035854](https://github.com/enjarai/mini-tardis/assets/101455696/a0ba7336-bee0-42ce-baaa-f4151cc87007)

[latest.log](https://github.com/enjarai/mini-tardis/files/14741136/latest.log)

**Comment by Nate4Fate** [comment]
I know it says Fabric 1.20.3, but I was using the mod on 1.20.1 on a modpack I was creating, so Mini Tardis on all versions adds crash-pipe.

**Comment by enjarai** [comment]
The crash pipe was intended to be a funny joke, but turned out to be not as fun as (and a lot louder than) anticipated. It'll be removed with the next update.

**Comment by enjarai** [comment]
Removed in the latest published version.
