### ISSUE TITLE
Experience lost on entering

### ISSUE THREAD

**Issue by SpaceNerd95251** [enjarai/mini-tardis#15]
When I enter the tardis, I lose all my levels

Modlist: https://pastebin.com/DNEmhiFC

**Comment by Benonardo** [comment]
It‘s a visual glitch with Minecraft itself (not specific to this mod). If you relog or wait a bit they should come back.

**Comment by enjarai** [comment]
Yup, problem in mc itself, not something I can/should fix.
See: https://bugs.mojang.com/browse/MC-124177
