### ISSUE TITLE
Valkryien Skies not compatable

### ISSUE THREAD

**Issue by rat123fuckthissititwasa** [enjarai/mini-tardis#32]
crashes while loading in
[crash-2024-11-20_21.19.38-client.txt](https://github.com/user-attachments/files/17835751/crash-2024-11-20_21.19.38-client.txt)
client side idk if its server side as well

**Comment by enjarai** [comment]
This crash looks like a problem with `ordinarycrook`. Mini Tardis or Valkyrien Skies are not involved.
